package com.od;

public class ODGetParkInfoQuery {
	
	//public static String SQL_GETPARKSINFO = "select * from Park_info where local_id=? and Is_active=0";

	public static String SQL_GETDATES = "select Date from Park_current_pricing_availability where Date=? "; 

	public static String SQL_GETPARKSINFO     ="select p.*,mpp.min_curr_price, mpp.Discount, mpp.Discount_mode, mpp.From_date, mpp.To_date from Park_info p,(select a.Park_id,a.min_curr_price, pd.Discount, pd.Discount_Mode, pd.From_date, pd.To_date from  (select Park_id,park_room_fac, min(Current_price) as min_curr_price from Park_current_pricing_availability cpv where date=? and Room_type_code='P'  group by Park_id)a	left join park_discount pd on a.Park_id=pd.Resort_id and a.park_room_fac = pd.park_room_fac and ? between pd.From_date and pd.To_date and pd.Status='A' ) mpp	where p.local_id=? and p.Parktype=? and p.Park_id=mpp.Park_id and p.Is_active=0";
	
	public static String SQL_GETPARKSROOMSINFO     ="select p.Appid,p.Parktype,p.Park_subcategory,p.Park_id,p.Overview_text,p.Faq,p.Name,p.OD_Rating,p.Metro,p.Local_area,p.Street_address,p.City,p.State,p.PIN,p.Description,p.Details,p.Latitude,p.Longitude,p.Type_string,p.Nature_string,p.Sub_category_string,p.Duration_string,p.Max_people,p.Popularity,p.Min_cost1_people,p.Min_cost2,p.Min_cost2_people,p.Special_offer_percentage,p.Special_rate,p.Main_photo_url,p.Park_sub_images,p.Amenities_string,p.Sponsored_featured_flag,p.Tag_name,p.Creation_date,p.Created_by,p.Updated_by,p.Video_Links,p.Policy_text,p.state_id,p.city_id,min(mpp.min_price), min(mpp.Discount), min(mpp.Discount_mode) from Park_info p,	(select a.park_id, a.min_price,pd.Discount, pd.Discount_Mode from (select pa1.park_id, pa1.park_room_fac, max(pa1.Current_price) as min_price from Park_current_pricing_availability pa1,(select Park_id, min(Current_price) as min_curr_price	from Park_current_pricing_availability where date between ? and ? and Room_type_code='P'  group by Park_id) pa2 where pa1. park_id=pa2.park_id and pa1.Current_price=pa2.min_curr_price group by pa1.park_id, pa1.park_room_fac)a left join park_discount pd on a.Park_id=pd.Resort_id  and a.park_room_fac = pd.park_room_fac and ? between pd.From_date and pd.To_date and pd.Status='A')mpp,(select Park_id,park_room_fac, count(*)  from Park_current_pricing_availability cpv  where date between ? and ?  and Current_available_qty>0  and Room_type_code='R'  group by Park_id,park_room_fac having count(*) = datediff(?,?)+1) rms	where p.local_id=?	and p.Parktype=? and p.Is_active=0 and p.Park_id=mpp.Park_id	and mpp.park_id=rms.park_id	group by p.Appid,p.Parktype,p.Park_subcategory,p.Park_id,p.Overview_text,p.Faq,p.Name,p.OD_Rating,p.Metro,p.Local_area,p.Street_address,p.City,p.State,p.PIN,p.Description,p.Details,p.Latitude,p.Longitude,p.Type_string,p.Nature_string,p.Sub_category_string,p.Duration_string,p.Max_people,p.Popularity,p.Min_cost1_people,p.Min_cost2,p.Min_cost2_people,p.Special_offer_percentage,p.Special_rate,p.Main_photo_url,p.Park_sub_images,p.Amenities_string,p.Sponsored_featured_flag,p.Tag_name,p.Creation_date,p.Created_by,p.Updated_by,p.Video_Links,p.Policy_text,p.state_id,p.city_id";
	
	public static String SQL_GETALLPARKSINFO = "SELECT p.*,mpp.min_curr_price, mpp.Discount, mpp.Discount_mode, mpp.From_date, mpp.To_date FROM Park_info p,(SELECT a.Park_id, a.min_curr_price, pd.Discount, pd.Discount_Mode, pd.From_date, pd.To_date FROM (SELECT Park_id, park_room_fac, MIN( Current_price ) AS min_curr_price FROM Park_current_pricing_availability cpv where  date=? and Room_type_code='P'  GROUP BY Park_id)a LEFT JOIN park_discount pd ON a.Park_id = pd.Resort_id AND a.park_room_fac = pd.park_room_fac AND  ? BETWEEN pd.From_date AND pd.To_date and pd.Status='A')mpp WHERE p.local_id =? AND p.Park_id = mpp.Park_id and p.Is_active=0";

	
	
	
	
	
	//public static String SQL_GETPARKSROOMSINFO ="SELECT p . * , mpp.min_curr_price, mpp.Discount, mpp.Discount_mode, mpp.From_date, mpp.To_date FROM Park_info p, (	SELECT a.Park_id, MIN( a.min_curr_price ) AS min_curr_price, pd.Discount, pd.Discount_Mode, pd.From_date, pd.To_date FROM (	SELECT Park_id, park_room_fac, MIN( Current_price ) AS min_curr_price, COUNT( * ) FROM Park_current_pricing_availability cpv WHERE DATE	BETWEEN  ?	AND  ?	AND Current_available_qty >0 AND Room_type_code =  'R'	GROUP BY Park_id, park_room_fac	HAVING COUNT( * ) = DATEDIFF(  ?,  ? ) +1	)a	LEFT JOIN park_discount pd ON a.Park_id = pd.Resort_id	GROUP BY a.park_id, pd.Discount, pd.Discount_Mode, pd.From_date, pd.To_date	)mpp WHERE p.local_id =?	AND p.Parktype = ?	AND p.Park_id = mpp.Park_id";
			


	//public static String SQL_GETPARKSROOMSINFO ="select p.*,mpp.min_curr_price, mpp.Discount, mpp.Discount_mode, mpp.From_date, mpp.To_date from Park_info p,(select a.Park_id,min(a.min_curr_price) as min_curr_price, pd.Discount, pd.Discount_Mode, pd.From_date, pd.To_date from (select Park_id,park_room_fac, min(Current_price) as min_curr_price, count(*) from Park_current_pricing_availability cpv where date between ? and ? and Current_available_qty>0 and Room_type_code='R' group by Park_id,park_room_fac having count(*) = datediff(?,?)+1)a left join park_discount pd on a.Park_id=pd.Resort_id and a.park_room_fac = pd.park_room_fac group by a.park_id,pd.Discount, pd.Discount_Mode, pd.From_date, pd.To_date) mpp where p.local_id=? and p.Parktype=? and p.Park_id=mpp.Park_id";
	
	
}